# Loading data

In [1]:
import pandas as pd

df = pd.read_csv('../data/raw/listings.csv.zst')
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,363601.0,NaN,2.025031e+13,2025-03-06,previous scrape,NaN,NaN,NaN,https://a0.muscache.com/pictures/38669984/67b5...,1837053.0,...,4.67,4.54,NaN,NaN,f,NaN,1.0,NaN,0.0,NaN
1,399772.0,https://www.nocarz.pl/rooms/399772,NaN,NaN,city scrape,Rocafort nice & bright 3 stops away Pza Cataluña,"Comfortable, nice and central two bedroom ap...",NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1995385.0,...,4.92,4.75,4.74,HUTB-001948,f,NaN,3.0,0.0,NaN,1.18
2,402369.0,https://www.nocarz.pl/rooms/402369,2.025031e+13,2025-03-11,NaN,Great 2 bedr flat close to Las Ramblas city ce...,Please send us a message to confirm availabili...,HAPPY NEIGHBOURHOOD<br />Located behind Paseo ...,https://a0.muscache.com/pictures/hosting/Hosti...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.07
3,456333.0,NaN,2.025031e+13,2025-03-06,previous scrape,DOUBLE ROOM with WIFI,NaN,NaN,NaN,2268672.0,...,4.95,4.83,4.88,NaN,f,NaN,0.0,1.0,0.0,0.26
4,NaN,https://www.nocarz.pl/rooms/480975,2.025031e+13,2025-03-07,previous scrape,Cozy loft with a big terrace!,"Real cozy loft, at an old factory from the beg...",NaN,https://a0.muscache.com/pictures/104020703/cd4...,NaN,...,NaN,NaN,NaN,NaN,f,NaN,0.0,1.0,0.0,NaN

In [7]:
df.shape

(1911, 79)

In [2]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [3]:
df.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,1.519000e+03,1.509000e+03,1.536000e+03,1508.000000,1520.000000,1545.000000,1533.000000,1559.000000,1145.000000,1365.00000,...,1097.000000,1127.000000,1111.000000,1122.000000,1112.000000,1507.000000,1538.000000,1531.000000,1555.000000,1121.000000
mean,5.647987e+17,2.025031e+13,2.115746e+08,65.423740,83.500000,41.392682,2.167260,3.368185,1.406987,1.80293,...,4.616235,4.710515,4.704167,4.758414,4.475612,50.750498,33.635891,13.719138,0.030225,1.348278
std,5.407685e+17,0.000000e+00,2.054804e+08,150.722089,183.851756,0.014190,0.017973,2.160543,0.797090,1.24257,...,0.528767,0.509745,0.534317,0.353575,0.577212,104.778005,87.320393,57.257401,0.328386,1.710819
min,1.882670e+05,2.025031e+13,1.070400e+04,1.000000,1.000000,41.335310,2.101617,1.000000,0.000000,0.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,3.235801e+07,2.025031e+13,1.491738e+07,2.000000,3.000000,41.381410,2.156800,2.000000,1.000000,1.00000,...,4.500000,4.665000,4.670000,4.670000,4.330000,2.000000,0.000000,0.000000,0.000000,0.200000
50%,6.448076e+17,2.025031e+13,1.522976e+08,8.000000,11.000000,41.391167,2.168040,3.000000,1.000000,2.00000,...,4.750000,4.860000,4.870000,4.850000,4.595000,8.000000,2.000000,0.000000,0.000000,0.660000
75%,1.104224e+18,2.025031e+13,3.671728e+08,42.000000,59.000000,41.402190,2.177600,4.000000,2.000000,2.00000,...,4.950000,5.000000,5.000000,5.000000,4.800000,38.000000,19.000000,2.000000,0.000000,2.010000
max,1.368636e+18,2.025031e+13,6.788518e+08,888.000000,2733.000000,41.452680,2.221830,16.000000,12.000000,24.00000,...,5.000000,5.000000,5.000000,5.000000,5.000000,483.000000,483.000000,399.000000,6.000000,20.260000

In [6]:
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1911 entries, 0 to 1910
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            1519 non-null   float64
 1   listing_url                                   1516 non-null   object
 2   scrape_id                                     1509 non-null   float64
 3   last_scraped                                  1523 non-null   object
 4   source                                        1556 non-null   object
 5   name                                          1512 non-null   object
 6   description                                   1461 non-null   object
 7   neighborhood_overview                         780 non-null    object
 8   picture_url                                   1522 non-null   object
 9   host_id                                       1536 non-null   float64
 10  host_url                                      1549 non-null   object
 11  host_name                                     1533 non-null   object
 12  host_since                                    1523 non-null   object
 13  host_location                                 1189 non-null   object
 14  host_about                                    966 non-null    object
 15  host_response_time                            1268 non-null   object
 16  host_response_rate                            1261 non-null   object
 17  host_acceptance_rate                          1291 non-null   object
 18  host_is_superhost                             1475 non-null   object
 19  host_thumbnail_url                            1537 non-null   object
 20  host_picture_url                              1520 non-null   object
 21  host_neighbourhood                            717 non-null    object
 22  host_listings_count                           1508 non-null   float64
 23  host_total_listings_count                     1520 non-null   float64
 24  host_verifications                            1539 non-null   object
 25  host_has_profile_pic                          1546 non-null   object
 26  host_identity_verified                        1516 non-null   object
 27  neighbourhood                                 753 non-null    object
 28  neighbourhood_cleansed                        1507 non-null   object
 29  neighbourhood_group_cleansed                  1530 non-null   object
 30  latitude                                      1545 non-null   float64
 31  longitude                                     1533 non-null   float64
 32  property_type                                 1533 non-null   object
 33  room_type                                     1549 non-null   object
 34  accommodates                                  1559 non-null   float64
 35  bathrooms                                     1145 non-null   float64
 36  bathrooms_text                                1554 non-null   object
 37  bedrooms                                      1365 non-null   float64
 38  beds                                          1216 non-null   float64
 39  amenities                                     1512 non-null   object
 40  price                                         1222 non-null   object
 41  minimum_nights                                1569 non-null   float64
 42  maximum_nights                                1546 non-null   float64
 43  minimum_minimum_nights                        1534 non-null   float64
 44  maximum_minimum_nights                        1529 non-null   float64
 45  minimum_maximum_nights                        1525 non-null   float64
 46  maximum_maximum_nights                        1504 non-null   float64
 47  minimum_nights_avg_ntm                        1526 non-null   float64
 48  maximum_nights_avg_ntm                        1537 non-null   float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              1446 non-null   object
 51  availability_30                               1504 non-null   float64
 52  availability_60                               1570 non-null   float64
 53  availability_90                               1563 non-null   float64
 54  availability_365                              1553 non-null   float64
 55  calendar_last_scraped                         1527 non-null   object
 56  number_of_reviews                             1518 non-null   float64
 57  number_of_reviews_ltm                         1503 non-null   float64
 58  number_of_reviews_l30d                        1496 non-null   float64
 59  availability_eoy                              1556 non-null   float64
 60  number_of_reviews_ly                          1510 non-null   float64
 61  estimated_occupancy_l365d                     1525 non-null   float64
 62  estimated_revenue_l365d                       1208 non-null   float64
 63  first_review                                  1101 non-null   object
 64  last_review                                   1118 non-null   object
 65  review_scores_rating                          1115 non-null   float64
 66  review_scores_accuracy                        1112 non-null   float64
 67  review_scores_cleanliness                     1097 non-null   float64
 68  review_scores_checkin                         1127 non-null   float64
 69  review_scores_communication                   1111 non-null   float64
 70  review_scores_location                        1122 non-null   float64
 71  review_scores_value                           1112 non-null   float64
 72  license                                       1000 non-null   object
 73  instant_bookable                              1513 non-null   object
 74  calculated_host_listings_count                1507 non-null   float64
 75  calculated_host_listings_count_entire_homes   1538 non-null   float64
 76  calculated_host_listings_count_private_rooms  1531 non-null   float64
 77  calculated_host_listings_count_shared_rooms   1555 non-null   float64
 78  reviews_per_month                             1121 non-null   float64
dtypes: float64(43), object(36)
memory usage: 1.2+ MB