# Loading data

In [77]:
import pandas as pd

df = pd.read_csv('../data/raw/Datafiniti_Hotel_Reviews.csv')

In [78]:
df

,id,dateAdded,dateUpdated,address,categories,primaryCategories,city,country,keys,latitude,...,reviews.dateSeen,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sourceURLs,websites
0,AVwc252WIN2L1WUfpqLP,2016-10-30T21:42:42Z,2018-09-10T21:06:27Z,5921 Valencia Cir,"Hotels,Hotels and motels,Hotel and motel reser...",Accommodation & Food Services,Rancho Santa Fe,US,us/ca/ranchosantafe/5921valenciacir/359754519,32.990959,...,"2016-08-03T00:00:00Z,2016-07-26T00:00:00Z,2016...",5.0,https://www.hotels.com/hotel/125419/reviews%20/,Our experience at Rancho Valencia was absolute...,Best romantic vacation ever!!!!,NaN,NaN,Paula,http://www.hotels.com/ho125419/%25252525253Flo...,http://www.ranchovalencia.com
1,AVwc252WIN2L1WUfpqLP,2016-10-30T21:42:42Z,2018-09-10T21:06:27Z,5921 Valencia Cir,"Hotels,Hotels and motels,Hotel and motel reser...",Accommodation & Food Services,Rancho Santa Fe,US,us/ca/ranchosantafe/5921valenciacir/359754519,32.990959,...,"2016-08-02T00:00:00Z,2016-08-26T00:00:00Z,2016...",5.0,https://www.hotels.com/hotel/125419/reviews%20/,Amazing place. Everyone was extremely warm and...,Sweet sweet serenity,NaN,NaN,D,http://www.hotels.com/ho125419/%25252525253Flo...,http://www.ranchovalencia.com
2,AVwc252WIN2L1WUfpqLP,2016-10-30T21:42:42Z,2018-09-10T21:06:27Z,5921 Valencia Cir,"Hotels,Hotels and motels,Hotel and motel reser...",Accommodation & Food Services,Rancho Santa Fe,US,us/ca/ranchosantafe/5921valenciacir/359754519,32.990959,...,"2016-11-15T00:00:00Z,2016-08-23T00:00:00Z,2016...",5.0,https://www.hotels.com/hotel/125419/reviews%20/,We booked a 3 night stay at Rancho Valencia to...,Amazing Property and Experience,NaN,NaN,Ron,http://www.hotels.com/ho125419/%25252525253Flo...,http://www.ranchovalencia.com
3,AVwdOclqIN2L1WUfti38,2015-11-28T19:19:35Z,2018-09-10T21:06:16Z,7520 Teague Rd,"Hotels,Hotels and motels,Travel agencies and b...",Accommodation & Food Services,Hanover,US,us/md/hanover/7520teaguerd/-2043779672,39.155929,...,"2016-05-21T00:00:00Z,2016-07-31T00:00:00Z",2.0,https://www.tripadvisor.com/Hotel_Review-g4118...,Currently in bed writing this for the past hr ...,"Never again...beware, if you want sleep.",Richmond,VA,jaeem2016,http://www.yellowbook.com/profile/aloft-arunde...,http://www.starwoodhotels.com/alofthotels/prop...
4,AVwdOclqIN2L1WUfti38,2015-11-28T19:19:35Z,2018-09-10T21:06:16Z,7520 Teague Rd,"Hotels,Hotels and motels,Travel agencies and b...",Accommodation & Food Services,Hanover,US,us/md/hanover/7520teaguerd/-2043779672,39.155929,...,2016-07-31T00:00:00Z,5.0,https://www.tripadvisor.com/Hotel_Review-g4118...,I live in Md and the Aloft is my Home away fro...,ALWAYS GREAT STAY...,Laurel,MD,MamaNiaOne,http://www.yellowbook.com/profile/aloft-arunde...,http://www.starwoodhotels.com/alofthotels/prop...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,AVwd4TMv_7pvs4fz-Ers,2016-03-24T11:44:15Z,2018-01-01T00:00:46Z,215 S Pacific St,"Hotel,Hotels,Lodging,Motels",Accommodation & Food Services,Rockaway Beach,US,us/or/rockawaybeach/215spacificst/-1035432852,45.611260,...,2016-03-23T00:00:00Z,3.0,http://www.tripadvisor.com/Hotel_Review-g52043...,It is hard for me to review an oceanfront hote...,Picture Window Ocean View!,Wildwood,GA,LASH0211,https://www.tripadvisor.com/Hotel_Review-g5204...,http://www.oregonsilversands.com
9996,AVwdRp4DIN2L1WUfuGZZ,2015-10-26T23:03:02Z,2018-01-01T00:00:44Z,669 Route 6a,"Hotel,Hotels",Accommodation & Food Services,East Sandwich,US,us/ma/eastsandwich/669route6a/-1480952475,41.729390,...,"2016-05-13T00:00:00Z,2016-03-21T00:00:00Z",4.0,https://www.tripadvisor.com/Hotel_Review-g4154...,"I live close by, and needed to stay somewhere ...","Clean, comfortable and quiet",East Sandwich,MA,Gennaker,https://www.tripadvisor.com/Hotel_Review-g4154...,http://www.sandyneck.com
9997,AVwd1TbkByjofQCxs6FH,2016-06-11T03:12:23Z,2018-01-01T00:00:44Z,702 W Appleway Ave,"Hotel,Hotel, Motel, and Building,Hotels,Lodgin...",Accommodation & Food Services,Coeur d'Alene,US,us/id/coeurd'alene/702wapplewayave/210547670,47.699930,...,2017-12-17T00:00:00Z,4.0,https://www.tripadvisor.com/Hotel_Review-g3541...,Rolled in 11:30 laid out heads down woke up to...,Passing through,Montana,UnitedStates,Amber406,https://www.tripadvisor.com/Hotel_Review-g3541...,http://www.shiloinns.com
9998,AVwdHbizIN2L1WUfsXto,2016-12-13T03:44:36Z,2018-01-01T00:00:43Z,2295 N Highland Ave,"Hotel,Hotels Motels,Budget Hotels,Hotels & Motels",Accommodation & Food Services,Jackson,US,us/tn/jackson/2295nhighlandave/1759289930,35.666390,...,2016-07-16T00:00:00Z,1.0,https://www.tripadvisor.com/Hotel_Review-g5512...,Absolutely terrible..I was told I was being gi...,Terrible,woodbury,NaN,donWoodbury,https://www.tripadvisor.com/Hotel_Review-g5512...,http://api.citygridmedia.com/content/places/v2...
9999,AVwddMfdIN2L1WUfwAue,2016-06-22T19:07:21Z,2018-01-01T00:00:43Z,3811 Minnesota Dr,"Hotel,Motels,Lodging,Hotels,Hotels and Motels",Accommodation & Food Services,Anchorage,US,us/ak/anchorage/3811minnesotadr/806029870,61.185310,...,2017-12-17T00:00:00Z,1.0,https://www.tripadvisor.com/Hotel_Review-g6088...,"Filthy, outdated, noisy neighbours, but this w...",Polde,Sempeter pri Gorici,Slovenia,janezr2013,https://www.tripadvisor.com/Hotel_Review-g6088...,http://royalsuitealaska.com

In [79]:
df.columns

Index(['id', 'dateAdded', 'dateUpdated', 'address', 'categories',
       'primaryCategories', 'city', 'country', 'keys', 'latitude', 'longitude',
       'name', 'postalCode', 'province', 'reviews.date', 'reviews.dateSeen',
       'reviews.rating', 'reviews.sourceURLs', 'reviews.text', 'reviews.title',
       'reviews.userCity', 'reviews.userProvince', 'reviews.username',
       'sourceURLs', 'websites'],
      dtype='object')

# Removing unnecessary columns

In [80]:
columns_to_drop = [
    'id',
    'dateAdded',
    'dateUpdated',
    'address',
    'categories',
    'primaryCategories',
    'city',
    'country',
    'keys',
    'latitude',
    'longitude',
    'name',
    'postalCode',
    'province',
    'reviews.date',
    'reviews.dateSeen',
    'reviews.sourceURLs',
    'reviews.title',
    'reviews.userCity',
    'reviews.userProvince',
    'reviews.username',
    'sourceURLs',
    'websites'
]

df = df.drop(labels=columns_to_drop, axis=1)

In [81]:
df

      reviews.rating                                       reviews.text
0                5.0  Our experience at Rancho Valencia was absolute...
1                5.0  Amazing place. Everyone was extremely warm and...
2                5.0  We booked a 3 night stay at Rancho Valencia to...
3                2.0  Currently in bed writing this for the past hr ...
4                5.0  I live in Md and the Aloft is my Home away fro...
...              ...                                                ...
9995             3.0  It is hard for me to review an oceanfront hote...
9996             4.0  I live close by, and needed to stay somewhere ...
9997             4.0  Rolled in 11:30 laid out heads down woke up to...
9998             1.0  Absolutely terrible..I was told I was being gi...
9999             1.0  Filthy, outdated, noisy neighbours, but this w...

[10000 rows x 2 columns]

# Renaming columns

In [82]:
df = df.rename(columns={'reviews.rating': 'numerical_review'})
df = df.rename(columns={'reviews.text': 'comments'})

In [83]:
df

      numerical_review                                           comments
0                  5.0  Our experience at Rancho Valencia was absolute...
1                  5.0  Amazing place. Everyone was extremely warm and...
2                  5.0  We booked a 3 night stay at Rancho Valencia to...
3                  2.0  Currently in bed writing this for the past hr ...
4                  5.0  I live in Md and the Aloft is my Home away fro...
...                ...                                                ...
9995               3.0  It is hard for me to review an oceanfront hote...
9996               4.0  I live close by, and needed to stay somewhere ...
9997               4.0  Rolled in 11:30 laid out heads down woke up to...
9998               1.0  Absolutely terrible..I was told I was being gi...
9999               1.0  Filthy, outdated, noisy neighbours, but this w...

[10000 rows x 2 columns]

# Removing empty rows

In [84]:
print('Data information:')
df.info(show_counts=True)

Data information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   numerical_review  10000 non-null  float64
 1   comments          9999 non-null   object
dtypes: float64(1), object(1)
memory usage: 156.4+ KB

In [85]:
df = df.dropna(subset=['comments', 'numerical_review'], how='any')

In [86]:
print('Data information:')
df.info(show_counts=True)

Data information:
<class 'pandas.core.frame.DataFrame'>
Index: 9999 entries, 0 to 9999
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   numerical_review  9999 non-null   float64
 1   comments          9999 non-null   object
dtypes: float64(1), object(1)
memory usage: 234.4+ KB

In [87]:
df

      numerical_review                                           comments
0                  5.0  Our experience at Rancho Valencia was absolute...
1                  5.0  Amazing place. Everyone was extremely warm and...
2                  5.0  We booked a 3 night stay at Rancho Valencia to...
3                  2.0  Currently in bed writing this for the past hr ...
4                  5.0  I live in Md and the Aloft is my Home away fro...
...                ...                                                ...
9995               3.0  It is hard for me to review an oceanfront hote...
9996               4.0  I live close by, and needed to stay somewhere ...
9997               4.0  Rolled in 11:30 laid out heads down woke up to...
9998               1.0  Absolutely terrible..I was told I was being gi...
9999               1.0  Filthy, outdated, noisy neighbours, but this w...

[9999 rows x 2 columns]

# Detecting reviews' languages

In [88]:
from langdetect import detect, DetectorFactory
from langdetect.lang_detect_exception import LangDetectException


DetectorFactory.seed = 0

def safe_detect(text):
    try:
        clean_text = text.strip()
        if len(clean_text) < 3:
            return 'unknown'
        return detect(clean_text)
    except LangDetectException:
        return 'unknown'

In [89]:
df.loc[:, 'language'] = df['comments'].apply(lambda x: safe_detect(x) if pd.notnull(x) else 'unknown')

/tmp/ipykernel_51842/1775370191.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'language'] = df['comments'].apply(lambda x: safe_detect(x) if pd.notnull(x) else 'unknown')

In [90]:
df['language'].unique()

array(['en', 'af', 'cy', 'so', 'it', 'es', 'da', 'de', 'fr', 'tl', 'no',
       'cs', 'vi', 'nl', 'fi', 'sv', 'ro', 'ca', 'sl', 'hr', 'pt', 'sk',
       'unknown'], dtype=object)

## Counting number of reviews in english

In [91]:
english_count = df['language'].value_counts().get('en', 0)
english_count

np.int64(9863)

## Removing non english reviews

In [92]:
df = df[df['language'] == 'en']

In [93]:
df['language'].unique()

array(['en'], dtype=object)

# Adding sentiment column

In [94]:
from textblob import TextBlob

df.loc[:, 'sentiment'] = df['comments'].apply(lambda x: TextBlob(str(x)).sentiment.polarity if pd.notna(x) else None)

/tmp/ipykernel_51842/1104060145.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'sentiment'] = df['comments'].apply(lambda x: TextBlob(str(x)).sentiment.polarity if pd.notna(x) else None)

In [95]:
df

,numerical_review,comments,language,sentiment
0,5.0,Our experience at Rancho Valencia was absolute...,en,0.589286
1,5.0,Amazing place. Everyone was extremely warm and...,en,0.375000
2,5.0,We booked a 3 night stay at Rancho Valencia to...,en,0.488889
3,2.0,Currently in bed writing this for the past hr ...,en,-0.125000
4,5.0,I live in Md and the Aloft is my Home away fro...,en,0.320501
...,...,...,...,...
9995,3.0,It is hard for me to review an oceanfront hote...,en,0.179500
9996,4.0,"I live close by, and needed to stay somewhere ...",en,0.281639
9997,4.0,Rolled in 11:30 laid out heads down woke up to...,en,0.382063
9998,1.0,Absolutely terrible..I was told I was being gi...,en,0.080000
9999,1.0,"Filthy, outdated, noisy neighbours, but this w...",en,-0.325000

# Adding column with length of review

In [96]:
df['review_length'] = df['comments'].str.len()

/tmp/ipykernel_51842/2025459387.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review_length'] = df['comments'].str.len()

In [97]:
df

,numerical_review,comments,language,sentiment,review_length
0,5.0,Our experience at Rancho Valencia was absolute...,en,0.589286,169
1,5.0,Amazing place. Everyone was extremely warm and...,en,0.375000,283
2,5.0,We booked a 3 night stay at Rancho Valencia to...,en,0.488889,471
3,2.0,Currently in bed writing this for the past hr ...,en,-0.125000,198
4,5.0,I live in Md and the Aloft is my Home away fro...,en,0.320501,307
...,...,...,...,...,...
9995,3.0,It is hard for me to review an oceanfront hote...,en,0.179500,339
9996,4.0,"I live close by, and needed to stay somewhere ...",en,0.281639,315
9997,4.0,Rolled in 11:30 laid out heads down woke up to...,en,0.382063,239
9998,1.0,Absolutely terrible..I was told I was being gi...,en,0.080000,338
9999,1.0,"Filthy, outdated, noisy neighbours, but this w...",en,-0.325000,224

# Assigining labels

In [98]:
def assign_label(row):
    return 1 if row['numerical_review'] <= 2 or row['sentiment'] < -0.3 else 0

In [99]:
df.loc[:, 'label'] = df.apply(assign_label, axis=1)

/tmp/ipykernel_51842/1091360543.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'label'] = df.apply(assign_label, axis=1)

In [100]:
df

,numerical_review,comments,language,sentiment,review_length,label
0,5.0,Our experience at Rancho Valencia was absolute...,en,0.589286,169,0
1,5.0,Amazing place. Everyone was extremely warm and...,en,0.375000,283,0
2,5.0,We booked a 3 night stay at Rancho Valencia to...,en,0.488889,471,0
3,2.0,Currently in bed writing this for the past hr ...,en,-0.125000,198,1
4,5.0,I live in Md and the Aloft is my Home away fro...,en,0.320501,307,0
...,...,...,...,...,...,...
9995,3.0,It is hard for me to review an oceanfront hote...,en,0.179500,339,0
9996,4.0,"I live close by, and needed to stay somewhere ...",en,0.281639,315,0
9997,4.0,Rolled in 11:30 laid out heads down woke up to...,en,0.382063,239,0
9998,1.0,Absolutely terrible..I was told I was being gi...,en,0.080000,338,1
9999,1.0,"Filthy, outdated, noisy neighbours, but this w...",en,-0.325000,224,1

# Reducing the data set

In [101]:
label_0_sample = df[df['label'] == 0].sample(n=200, random_state=42)
other_labels = df[df['label'] != 0]
df = pd.concat([label_0_sample, other_labels])

In [102]:
label_1_sample = df[df['label'] == 1].sample(n=100, random_state=42)
other_labels = df[df['label'] != 1]
df = pd.concat([label_1_sample, other_labels])

In [103]:
df

,numerical_review,comments,language,sentiment,review_length,label
1512,3.0,I didn't notice that this hotel room has share...,en,-0.780000,90,1
2882,1.0,"The old Aztec Hotel on foothill blvd, ( route ...",en,-0.058660,459,1
9386,1.0,I understand these cabins are 75 years old so ...,en,0.301389,298,1
1547,1.0,Two positives: the front desk staff and the lo...,en,-0.016667,912,1
6143,2.0,We chose this facility based on location and w...,en,-0.325000,268,1
...,...,...,...,...,...,...
7118,3.0,"As other reviewers stated, the staff here is a...",en,0.062500,313,0
8572,5.0,I recently stayed the night at this motel and ...,en,0.391515,335,0
3662,4.6,Bad: Probably my oversight when Iread the desc...,en,0.273611,278,0
2522,4.0,"We enjoyed our stay a this property, all staff...",en,0.446771,347,0
9790,4.0,"quiet room, quick check-in, easy parking,hotel...",en,0.358333,112,0

# Saving prepared data

In [104]:
df.to_csv('../data/processed/hotel_reviews.csv', index=False)